import { useCallback, useEffect, useState } from 'react';
import { recipeAllergens } from '../data/recipe-allergens.js';

async function request(body, method = 'GET') {
  const response = await fetch('/api/admin/recipes', { method, credentials: 'same-origin', cache: 'no-store', ...(body ? { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}) });
  const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Não foi possível salvar a receita.'); return result;
}
const blank = { title: '', category: 'doce', summary: '', ingredientsText: '', preparationText: '', imageUrl: '', imageAlt: '', note: '', servings: '', prepMinutes: '', productIds: ['7-receitas-desinflamar'], published: false, allergenIds: [], imageAuthor: '', imageSource: '', imageLicense: '', nutrition: { kcal: '', protein: '', carbs: '', fat: '', source: '' } };
const editable = item => ({ ...blank, ...item, imageAuthor: item.imageAuthor || item.image?.credit?.author || '', imageSource: item.imageSource || item.image?.credit?.sourceUrl || '', imageLicense: item.imageLicense || item.image?.credit?.license || '', imageUrl: item.imageUrl || item.image?.src || item.image?.url || '', imageAlt: item.imageAlt || item.image?.alt || item.title, ingredientsText: item.ingredientsText || (item.ingredients || []).map(ingredient => typeof ingredient === 'string' ? ingredient : ingredient.display || `${ingredient.quantity || ''} ${ingredient.name || ''}`.trim()).join('\n'), preparationText: item.preparationText || (item.preparation || []).join('\n'), nutrition: { ...blank.nutrition, ...item.nutrition } });
export function AdminRecipes({ onEditingStateChange }) {
  const [data, setData] = useState(null); const [form, setForm] = useState(null); const [query, setQuery] = useState(''); const [collection, setCollection] = useState('all'); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [dirty, setDirty] = useState(false);
  const load = useCallback(async () => { try { setData(await request()); } catch (error) { setMessage(error.message); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { onEditingStateChange?.({ dirty, busy }); }, [dirty, busy, onEditingStateChange]);
  useEffect(() => () => { onEditingStateChange?.({ dirty: false, busy: false }); }, [onEditingStateChange]);
  useEffect(() => { if (!dirty) return; const handler = event => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty]);
  const edit = (key, value) => { setForm(current => ({ ...current, [key]: value })); setDirty(true); };
  const open = value => { if (!dirty || window.confirm('Descartar as alterações desta receita que ainda não foram salvas?')) { setForm(editable(value)); setDirty(false); setMessage(''); } };
  const save = async event => {
    event.preventDefault(); setBusy(true); setMessage('');
    try { const nutrition = form.nutrition.source?.trim() ? Object.fromEntries(Object.entries(form.nutrition).map(([key,value]) => [key, key === 'source' ? value : value === '' || value === null ? null : Number(value)])) : null;
      const result = await request({ recipe: { ...form, servings: form.servings === '' ? null : Number(form.servings), prepMinutes: form.prepMinutes === '' ? null : Number(form.prepMinutes), nutrition } }, form.id ? 'PATCH' : 'POST');
      setForm(editable(result.recipe || form)); setDirty(false); await load(); setMessage('Receita salva. As próximas entregas usarão esta versão.');
    } catch (error) { setMessage(error.message); } finally { setBusy(false); }
  };
  const list = (data?.recipes || []).filter(item => (collection === 'all' || item.productIds?.includes(collection)) && `${item.title} ${item.summary}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
  return <section id="receitas" className="admin-section nw"><div className="nw-heading"><div><p className="admin-label">Conteúdo dos seus produtos</p><h2>Seu livro, sempre vivo.</h2></div><div className="nw-actions"><button className="nw-button nw-button--quiet" disabled={busy} onClick={async () => { if (dirty && !window.confirm('Descartar as alterações da receita e carregar o catálogo salvo?')) return; setForm(null); setDirty(false); await load(); }}>Atualizar catálogo</button><button className="nw-button" disabled={busy || !data} onClick={() => open(structuredClone(blank))}>+ Nova receita</button></div></div><p className="nw-intro">Edite ingredientes, preparo, fotografias e quais livros incluem cada receita. Você também pode manter uma receita em rascunho enquanto revisa.</p>{message && <p className="nw-notice" role="status">{message}</p>}
    <div className="nw-toolbar"><label className="nw-search">Buscar receita<input type="search" value={query} onChange={event => setQuery(event.target.value)} /></label><label>Coleção<select value={collection} onChange={event => setCollection(event.target.value)}><option value="all">Todas as coleções</option>{data?.products?.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label></div>
    {!data ? <p>Carregando receitas…</p> : <div className="nw-recipe-manager"><div className="nw-recipe-list">{list.map(item => <button className={form?.id === item.id ? 'is-active' : ''} key={item.id} onClick={() => open(item)} disabled={busy}><img src={item.imageUrl || item.image?.src || item.image?.url} alt="" loading="lazy" /><span><strong>{item.title}</strong><small>{item.published ? 'Disponível no livro' : 'Rascunho'} · {item.category}</small></span></button>)}{!list.length && <p>Nenhuma receita encontrada.</p>}</div>{form ? <form className="nw-card nw-form" onSubmit={save}><fieldset className="nw-editor nw-form" disabled={busy}><div className="nw-grid-2"><label>Título<input required maxLength="120" value={form.title} onChange={event => edit('title', event.target.value)} /></label><label>Categoria<select value={form.category} onChange={event => edit('category', event.target.value)}><option value="doce">Doce</option><option value="salgada">Salgada</option><option value="bebida">Bebida</option></select></label></div><label>Apresentação<textarea rows="3" maxLength="1000" value={form.summary} onChange={event => edit('summary', event.target.value)} /></label><div className="nw-grid-2"><label>Porções<input type="number" min="1" max="100" value={form.servings ?? ''} onChange={event => edit('servings', event.target.value)} /></label><label>Tempo de preparo (minutos)<input type="number" min="1" max="1440" value={form.prepMinutes ?? ''} onChange={event => edit('prepMinutes', event.target.value)} /></label></div><label>Ingredientes · um por linha<textarea required rows="8" value={form.ingredientsText} onChange={event => edit('ingredientsText', event.target.value)} placeholder="1 banana madura\n1 colher (sopa) de cacau" /></label><label>Preparo · uma etapa por linha<textarea required rows="8" value={form.preparationText} onChange={event => edit('preparationText', event.target.value)} /></label><label>Fotografia real · endereço<input maxLength="500" value={form.imageUrl} onChange={event => edit('imageUrl', event.target.value)} placeholder="/images/recipes/minha-receita.jpg" /></label><p className="nw-fine">Fotos do site (/images/…), images.unsplash.com ou images.pexels.com. Use uma foto que corresponda ao preparo.</p><label>Descrição da fotografia<input maxLength="200" value={form.imageAlt || ''} onChange={event => edit('imageAlt', event.target.value)} /></label>{form.imageUrl && <img className="nw-content-photo" src={form.imageUrl} alt={form.imageAlt || form.title} />}<label>Observações da nutricionista<textarea rows="3" maxLength="2000" value={form.note || ''} onChange={event => edit('note', event.target.value)} /></label>
      <details><summary>Alérgenos e créditos da fotografia</summary><fieldset><legend>Alérgenos presentes</legend>{Object.entries(recipeAllergens).map(([id, allergen]) => <label className="nw-check" key={id}><input type="checkbox" checked={form.allergenIds?.includes(id) || false} onChange={event => edit('allergenIds', event.target.checked ? [...(form.allergenIds || []), id] : form.allergenIds.filter(value => value !== id))} />{allergen.label}</label>)}</fieldset>{[['imageAuthor','Autor da fotografia'],['imageSource','Endereço da fonte'],['imageLicense','Licença ou autorização de uso']].map(([key,label]) => <label key={key}>{label}<input maxLength={key === 'imageSource' ? 1500 : 300} value={form[key] || ''} onChange={event => edit(key, event.target.value)} /></label>)}</details>
      <details><summary>Informações nutricionais por porção</summary><p className="nw-fine">Inclua somente valores calculados ou conferidos. Sem uma fonte, os valores não serão publicados.</p><div className="nw-grid-2">{[['kcal','Energia (kcal)'],['protein','Proteínas (g)'],['carbs','Carboidratos (g)'],['fat','Gorduras (g)']].map(([key,label]) => <label key={key}>{label}<input type="number" min="0" step="0.1" value={form.nutrition?.[key] ?? ''} onChange={event => edit('nutrition', { ...form.nutrition, [key]: event.target.value })} /></label>)}</div><label>Fonte ou memória do cálculo<input maxLength="500" value={form.nutrition?.source || ''} onChange={event => edit('nutrition', { ...form.nutrition, source: event.target.value })} /></label></details>
      <fieldset><legend>Incluir nas coleções</legend>{data.products.map(item => <label className="nw-check" key={item.id}><input type="checkbox" checked={form.productIds?.includes(item.id) || false} onChange={event => edit('productIds', event.target.checked ? [...(form.productIds || []), item.id] : form.productIds.filter(id => id !== item.id))} />{item.title}</label>)}</fieldset><label className="nw-check"><input type="checkbox" checked={form.published === true} onChange={event => edit('published', event.target.checked)} />Conteúdo revisado · disponibilizar nos livros selecionados</label><div className="nw-actions"><button className="nw-button">{busy ? 'Salvando…' : 'Salvar receita'}</button>{form.id && <button type="button" className="nw-button nw-button--quiet" onClick={() => { const copy = { ...form, title: `${form.title} · cópia`, published: false }; delete copy.id; setForm(copy); setDirty(true); }}>Duplicar receita</button>}</div></fieldset></form> : <div className="nw-empty"><h3>Escolha uma receita para começar.</h3><p>As alterações ficam salvas no painel e são refletidas nos arquivos entregues.</p></div>}</div>}
  </section>;
}
