import { useCallback, useEffect, useState } from 'react';
import { nutritionApi } from './NutritionPublic.jsx';
import { allergies, foods } from '../data/nutrition.js';
const api = (action, body) => nutritionApi(action, body, true);
const types = [['tea','Chá'],['recipe','Receita complementar'],['food','Alimento'],['seasoning','Tempero'],['supplement','Suplemento']];
export function NutritionContentLibrary({ onEditingStateChange }) {
  const [library, setLibrary] = useState(null); const [selection, setSelection] = useState(null); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [dirty, setDirty] = useState(false);
  const load = useCallback(async () => { try { setLibrary(await api('library')); } catch (error) { setMessage(error.message); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { onEditingStateChange?.({ dirty, busy }); }, [dirty, busy, onEditingStateChange]);
  useEffect(() => () => { onEditingStateChange?.({ dirty: false, busy: false }); }, [onEditingStateChange]);
  useEffect(() => { if (!dirty) return; const handler = event => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', handler); return () => window.removeEventListener('beforeunload', handler); }, [dirty]);
  const edit = (key, value) => { setSelection(current => ({ ...current, [key]: value })); setDirty(true); };
  const open = item => { if (!dirty || window.confirm('Descartar as alterações ainda não salvas?')) { setSelection(structuredClone(item)); setDirty(false); setMessage(''); } };
  const save = async remove => {
    setBusy(true); setMessage('');
    const exists = library.modules.some(item => item.id === selection.id);
    const modules = remove ? library.modules.filter(item => item.id !== selection.id) : exists ? library.modules.map(item => item.id === selection.id ? selection : item) : [...library.modules, selection];
    try { const result = await api('library-save', { modules, revision: library.revision }); setLibrary(result); setDirty(false); if (remove) setSelection(null); setMessage(remove ? 'Conteúdo removido da biblioteca.' : 'Conteúdo salvo. Disponível para adaptar nos próximos planos.'); }
    catch (error) { setMessage(error.message); } finally { setBusy(false); }
  };
  return <section className="nw-content-library"><div className="nw-heading"><div><p className="admin-label">Sua curadoria, sempre à mão</p><h2>Chás e complementos.</h2></div><button className="nw-button" disabled={!library || busy} onClick={() => open({ id: crypto.randomUUID(), type: 'tea', title: '', content: '', image: '', foodIds: [], allergens: [], requiresIngredientReview: true })}>+ Novo conteúdo</button></div><p className="nw-intro">Cadastre fotografias, preparos e orientações para reaproveitar nos atendimentos. Cada indicação será revisada para a pessoa antes da entrega.</p>{message && <p className="nw-notice" role="status">{message}</p>}
      {!library ? <p>Carregando biblioteca…</p> : <div className="nw-grid-2"><div className="nj-content-ideas">{library.modules.map(item => <article key={item.id}>{item.image && <img className="nw-content-photo" src={item.image} alt={item.title} loading="lazy" />}<p className="admin-label">{types.find(([id]) => id === item.type)?.[1]}</p><h3>{item.title}</h3><p>{item.content}</p><button className="nw-button nw-button--quiet" disabled={busy} onClick={() => open(item)}>Editar</button></article>)}</div>{selection && <form className="nw-card nw-form" onSubmit={event => { event.preventDefault(); save(false); }}><fieldset className="nw-editor nw-form" disabled={busy}><label>Tipo<select value={selection.type} onChange={event => edit('type', event.target.value)}>{types.map(([id,label]) => <option key={id} value={id}>{label}</option>)}</select></label><label>Nome<input required maxLength="120" value={selection.title} onChange={event => edit('title', event.target.value)} /></label><label>Orientação e preparo<textarea required rows="8" maxLength="3000" value={selection.content} onChange={event => edit('content', event.target.value)} /></label><label>Endereço da fotografia real<input maxLength="500" value={selection.image || ''} onChange={event => edit('image', event.target.value)} placeholder="/images/teas/chamomile.jpg" /></label><p className="nw-fine">Fotos do site (/images/…), images.unsplash.com ou images.pexels.com. Confira se a fotografia mostra o ingrediente correto.</p>{selection.image && <img className="nw-content-photo" src={selection.image} alt={selection.title} />}<label>Ingredientes do catálogo<select multiple size="6" value={selection.foodIds} onChange={event => edit('foodIds', [...event.target.selectedOptions].map(item => item.value))}>{foods.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><fieldset><legend>Alérgenos</legend>{allergies.filter(item => item.id !== 'other').map(item => <label className="nw-check" key={item.id}><input type="checkbox" checked={selection.allergens.includes(item.id)} onChange={event => edit('allergens', event.target.checked ? [...selection.allergens, item.id] : selection.allergens.filter(id => id !== item.id))} />{item.label}</label>)}</fieldset><div className="nw-actions"><button className="nw-button">{busy ? 'Salvando…' : 'Salvar conteúdo'}</button><button type="button" className="nw-button nw-button--quiet" onClick={() => { if (window.confirm('Remover este conteúdo da biblioteca? Os planos anteriores ficam preservados.')) save(true); }}>Remover</button></div></fieldset></form>}</div>}
    </section>;
}
