import { bmiInterpretation, skinfoldEvaluation } from '../lib/nutrition-clinical.js';
const format = value => value == null || !Number.isFinite(Number(value)) ? '—' : Number(value).toLocaleString('pt-BR', { maximumFractionDigits: 2 });
export function ClinicalMeasurementFields({ values, onChange }) {
  const result = skinfoldEvaluation(values); const bmi = bmiInterpretation(values);
  const sites = values.sex === 'male' ? [['chest','Peitoral'],['abdomen','Abdominal'],['thigh','Coxa']] : [['triceps','Tríceps'],['suprailiac','Supra-ilíaca'],['thigh','Coxa']];
  return <section className="nw-form"><div className="nw-clinical-status"><span className="admin-label">Avaliação atual</span>{bmi && <><h3>{bmi.label}</h3><p>IMC {format(bmi.value)} kg/m²</p><p className="nw-fine">{bmi.note}</p></>}</div>
    <details><summary>Dobras cutâneas e composição corporal</summary><p className="nw-fine">Registre a média de duas ou três medidas, feitas com adipômetro pela profissional. Estes campos não estimam dobras por fotografia.</p><div className="nw-grid-2"><label>Data das medidas<input type="date" value={values.measurementDate || ''} onChange={event => onChange(current => ({ ...current, measurementDate: event.target.value }))} /></label><label>Método<select value={values.skinfoldMethod || ''} onChange={event => onChange(current => ({ ...current, skinfoldMethod: event.target.value }))}><option value="">Sem estimativa por dobras</option><option value="jackson-pollock-3">Jackson & Pollock · 3 dobras + Siri</option></select></label></div>{values.skinfoldMethod === 'jackson-pollock-3' && <><div className="nw-grid-3">{sites.map(([key,label]) => <label key={key}>{label} · média (mm)<input type="number" min="1" max="80" step="0.1" value={values.skinfolds?.[key] ?? ''} onChange={event => onChange(current => ({ ...current, skinfolds: { ...current.skinfolds, [key]: event.target.value === '' ? '' : Number(event.target.value) } }))} /></label>)}</div>{result ? <div className="nw-calc-results">{[['Soma das dobras',result.sum,'mm'],['Densidade corporal',result.density,'g/cm³'],['Gordura estimada',result.bodyFat,'%'],['Massa de gordura',result.fatMass,'kg'],['Massa livre de gordura',result.leanMass,'kg']].map(([label,value,unit]) => <div key={label}><small>{label}</small><strong>{format(value)}</strong><span>{unit}</span></div>)}</div> : <p className="nw-notice">Preencha as três dobras, a data e as medidas válidas. A estimativa requer referência feminina (18–55 anos) ou masculina (18–61 anos), fora da gestação.</p>}</>}
    <label>Origem do percentual de gordura informado<input maxLength="120" value={values.bodyFatMethod || ''} onChange={event => onChange(current => ({ ...current, bodyFatMethod: event.target.value }))} placeholder="Ex.: bioimpedância, aparelho e condições da avaliação" /></label></details>
  </section>;
}
export function PlateGuideEditor({ value, onChange, disabled }) {
  const total = value ? Object.values(value).reduce((sum, number) => sum + Number(number || 0), 0) : 0;
  return <section className="nw-card nw-form"><p className="admin-label">Composição visual no prato</p><h3>A proporção que você orienta.</h3><p className="nw-fine">As fotos de alimentos ilustram os grupos no prato do HTML e do PDF. As porcentagens indicam a distribuição visual orientada, e não a proporção de macronutrientes ou gramas.</p><label className="nw-check"><input type="checkbox" checked={Boolean(value)} disabled={disabled} onChange={event => onChange(event.target.checked ? { protein: 25, carbs: 25, vegetables: 50 } : null)} />Definir proporções personalizadas no prato</label>{value && <><div className="nw-grid-3">{[['protein','Proteínas e leguminosas'],['carbs','Cereais e raízes'],['vegetables','Vegetais']].map(([key,label]) => <label key={key}>{label} (%)<input type="number" min="0" max="100" step="1" disabled={disabled} value={value[key]} onChange={event => onChange({ ...value, [key]: Number(event.target.value) })} /></label>)}</div><p className={Math.abs(total - 100) > .1 ? 'nw-notice' : 'nw-fine'}>Total: {total}%. {Math.abs(total - 100) > .1 ? 'Ajuste para 100% antes de salvar.' : 'Distribuição pronta para a entrega.'}</p></>}</section>;
}
